language: python
python:
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"
install:
  - pip install -r tests/requirements.txt    
script:
  - pytest --cov-report=xml --cov=mlworks tests/
after_success:
  - codecov